export interface RecordField {
    name: string;
    type: 'text' | 'textarea' | 'number' | 'date' | 'email' | 'tel' | 'select' | 'checkbox' | 'signature' | 'currency' | 'rating';
    required?: boolean | 'conditional';
    maxLength?: number;
    pattern?: string;
    min?: number;
    max?: number;
    options?: string[];
    defaultValue?: string | number;
    autoGenerated?: boolean;
    autoFill?: boolean;
    calculated?: boolean;
    readOnly?: boolean;
    formula?: string;
    currency?: string;
    scale?: string;
    placeholder?: string;
}

export interface RecordSection {
    title: string;
    type?: 'normal' | 'repeatable' | 'workflow' | 'rating';
    fields?: RecordField[];
    criteria?: Array<{
        category: string;
        items: Array<{
            criterion: string;
            weight: number;
        }>;
    }>;
    approvers?: Array<{
        role: string;
        condition?: string;
        required: boolean | 'conditional';
    }>;
}

export interface PolicyLimit {
    dailyLimit?: number;
    perMeal?: number;
    perNight?: number;
    perEvent?: number;
    requiresReceipt?: boolean;
    requiresApproval?: boolean;
}

export interface ManagementRecord {
    id: string;
    title: string;
    department: 'Finance' | 'HR' | 'Sales' | 'Operations' | 'Inventory' | 'Administrative' | 'Quality';
    category: string;
    version: string;
    effectiveDate: string;
    approvedBy?: string;
    description: string;
    formStructure: {
        sections: RecordSection[];
    };
    instructions?: string[];
    validationRules?: string[];
    relatedDocuments?: string[];
    policyLimits?: Record<string, PolicyLimit>;
    leavePolicy?: any;
}
