import { StyleSheet } from '@react-pdf/renderer';

export const pdfStyles = StyleSheet.create({
    page: {
        padding: 50,
        backgroundColor: '#ffffff',
        fontFamily: 'Helvetica',
        fontSize: 11,
    },
    coverPage: {
        padding: 60,
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
    },
    coverTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#111827',
        marginBottom: 12,
        textAlign: 'center',
    },
    coverCategory: {
        fontSize: 12,
        color: '#6b7280',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 24,
    },
    coverSubtitle: {
        fontSize: 10,
        color: '#9ca3af',
        marginTop: 32,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    headerLeft: { fontSize: 9, color: '#6b7280' },
    headerRight: { fontSize: 9, color: '#6b7280' },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 50,
        right: 50,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: '#e5e7eb',
        fontSize: 9,
        color: '#9ca3af',
    },
    section: { marginBottom: 16 },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#111827',
        marginBottom: 8,
        paddingBottom: 4,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    subsectionTitle: {
        fontSize: 13,
        fontWeight: 'bold',
        color: '#374151',
        marginTop: 12,
        marginBottom: 6,
    },
    paragraph: {
        fontSize: 11,
        color: '#4b5563',
        lineHeight: 1.5,
        marginBottom: 8,
    },
    listItem: {
        flexDirection: 'row',
        marginBottom: 4,
        fontSize: 11,
        color: '#4b5563',
    },
    bullet: { marginRight: 8 },
    table: { width: '100%', marginBottom: 12 },
    tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
    tableHeader: { flexDirection: 'row', borderBottomWidth: 2, borderBottomColor: '#111827', marginBottom: 4 },
    tableCell: { flex: 1, padding: 6, fontSize: 10 },
    tableCellHeader: { flex: 1, padding: 6, fontSize: 10, fontWeight: 'bold' },
    fieldLabel: { fontSize: 10, fontWeight: 'bold', color: '#374151', marginBottom: 2 },
    fieldValue: { fontSize: 10, color: '#4b5563', marginBottom: 8 },
    signatureBox: {
        width: 120,
        height: 40,
        borderWidth: 1,
        borderColor: '#d1d5db',
        marginTop: 4,
        marginBottom: 12,
    },
});
