import { ManagementRecord } from '../../types/records';

export const adminRecords: ManagementRecord[] = [
    {
        id: 'ADMIN-001',
        title: 'Meeting Minutes Template',
        department: 'Administrative',
        category: 'Documentation',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Template for recording meeting minutes',
        formStructure: {
            sections: [
                { title: 'Meeting Details', fields: [
                    { name: 'Meeting Title', type: 'text', required: true },
                    { name: 'Date', type: 'date', required: true },
                    { name: 'Start Time', type: 'text', required: true },
                    { name: 'End Time', type: 'text', required: true },
                    { name: 'Location', type: 'text', required: true },
                    { name: 'Chair', type: 'text', required: true },
                    { name: 'Minute Taker', type: 'text', required: true }
                ]},
                { title: 'Attendees', fields: [
                    { name: 'Attendees', type: 'textarea', required: true },
                    { name: 'Apologies', type: 'textarea' }
                ]},
                { title: 'Agenda & Minutes', fields: [
                    { name: 'Agenda Items', type: 'textarea', required: true },
                    { name: 'Discussion Summary', type: 'textarea', required: true },
                    { name: 'Decisions', type: 'textarea', required: true },
                    { name: 'Action Items', type: 'textarea', required: true }
                ]},
                { title: 'Sign-off', fields: [
                    { name: 'Chair Signature', type: 'signature', required: true },
                    { name: 'Date', type: 'date', required: true }
                ]}
            ]
        },
        instructions: ['Distribute within 48 hours', 'Store in shared drive', 'Follow up on action items'],
        relatedDocuments: ['Company Manual', 'Document Control']
    },
    {
        id: 'ADMIN-002',
        title: 'Business Correspondence Template',
        department: 'Administrative',
        category: 'Documentation',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Template for formal business correspondence',
        formStructure: {
            sections: [
                { title: 'Header', fields: [
                    { name: 'Reference', type: 'text', required: true },
                    { name: 'Date', type: 'date', required: true, defaultValue: 'today' },
                    { name: 'To', type: 'textarea', required: true },
                    { name: 'From', type: 'text', required: true },
                    { name: 'Subject', type: 'text', required: true }
                ]},
                { title: 'Body', fields: [
                    { name: 'Body', type: 'textarea', required: true, maxLength: 2000 }
                ]},
                { title: 'Sign-off', fields: [
                    { name: 'Author Signature', type: 'signature', required: true },
                    { name: 'Author Name & Title', type: 'text', required: true }
                ]}
            ]
        },
        instructions: ['Use for formal letters', 'Keep copy on file', 'Follow company letterhead when applicable'],
        relatedDocuments: ['Company Manual', 'Document Control']
    },
    {
        id: 'ADMIN-003',
        title: 'Document Request Form',
        department: 'Administrative',
        category: 'Documentation',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Form to request internal or external documents',
        formStructure: {
            sections: [
                { title: 'Request', fields: [
                    { name: 'Request Number', type: 'text', autoGenerated: true },
                    { name: 'Date', type: 'date', required: true, defaultValue: 'today' },
                    { name: 'Requested By', type: 'text', required: true },
                    { name: 'Department', type: 'select', required: true, options: ['Sales', 'Operations', 'Finance', 'HR', 'Admin'] },
                    { name: 'Document Description', type: 'textarea', required: true },
                    { name: 'Purpose', type: 'textarea', required: true },
                    { name: 'Urgency', type: 'select', required: true, options: ['Normal', 'Urgent', 'Same Day'] }
                ]},
                { title: 'Fulfilment', fields: [
                    { name: 'Provided By', type: 'text' },
                    { name: 'Date Provided', type: 'date' },
                    { name: 'Method', type: 'select', options: ['Email', 'Hard Copy', 'Shared Drive', 'Other'] }
                ]}
            ]
        },
        instructions: ['Submit to document owner or Admin', 'Confidential documents require approval', 'Log all requests'],
        relatedDocuments: ['Company Manual', 'Document Control']
    },
    {
        id: 'ADMIN-004',
        title: 'Access Request/Change Form',
        department: 'Administrative',
        category: 'IT & Security',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Form to request or change system or physical access',
        formStructure: {
            sections: [
                { title: 'Request', fields: [
                    { name: 'Request Number', type: 'text', autoGenerated: true },
                    { name: 'Date', type: 'date', required: true, defaultValue: 'today' },
                    { name: 'Requested By', type: 'text', required: true },
                    { name: 'Employee / Contractor', type: 'text', required: true },
                    { name: 'Type', type: 'select', required: true, options: ['New Access', 'Access Change', 'Access Revocation'] },
                    { name: 'System / Area', type: 'text', required: true },
                    { name: 'Justification', type: 'textarea', required: true }
                ]},
                { title: 'Approval', fields: [
                    { name: 'Manager Approval', type: 'signature', required: true },
                    { name: 'IT / Admin Approval', type: 'signature', required: true },
                    { name: 'Date Processed', type: 'date' }
                ]}
            ]
        },
        instructions: ['Manager approval required', 'Revocation processed on exit', 'Review access periodically'],
        relatedDocuments: ['Company Manual', 'People & Admin Playbook']
    },
    {
        id: 'ADMIN-005',
        title: 'Asset Request Form',
        department: 'Administrative',
        category: 'Assets',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Form to request company assets (equipment, etc.)',
        formStructure: {
            sections: [
                { title: 'Request', fields: [
                    { name: 'Request Number', type: 'text', autoGenerated: true },
                    { name: 'Date', type: 'date', required: true, defaultValue: 'today' },
                    { name: 'Requested By', type: 'text', required: true },
                    { name: 'Department', type: 'text', required: true },
                    { name: 'Asset Type', type: 'select', required: true, options: ['Laptop', 'Phone', 'Vehicle', 'Tool', 'Other'] },
                    { name: 'Description', type: 'textarea', required: true },
                    { name: 'Justification', type: 'textarea', required: true }
                ]},
                { title: 'Approval', fields: [
                    { name: 'Manager Approval', type: 'signature', required: true },
                    { name: 'Admin / Finance Approval', type: 'signature', required: 'conditional' },
                    { name: 'Asset Tag / ID', type: 'text' },
                    { name: 'Date Issued', type: 'date' }
                ]}
            ]
        },
        instructions: ['Obtain approvals per policy', 'Record asset tag on issue', 'Return on separation'],
        relatedDocuments: ['Company Manual', 'People & Admin Playbook']
    }
];
