import { ManagementRecord } from '../../types/records';

export const financialRecords: ManagementRecord[] = [
    {
        id: 'FIN-001',
        title: 'Purchase Order Form',
        department: 'Finance',
        category: 'Procurement',
        version: '2.1',
        effectiveDate: '2024-01-15',
        approvedBy: 'Finance Director',
        description: 'Standard form for initiating purchase requests and orders for goods and services',

        formStructure: {
            sections: [
                {
                    title: 'Vendor Information',
                    fields: [
                        { name: 'Vendor Name', type: 'text', required: true, maxLength: 100 },
                        { name: 'Vendor Code', type: 'text', required: true, pattern: '^V[0-9]{5}$' },
                        { name: 'Vendor Address', type: 'textarea', required: true, maxLength: 300 },
                        { name: 'Contact Person', type: 'text', required: true, maxLength: 100 },
                        { name: 'Phone Number', type: 'tel', required: true },
                        { name: 'Email', type: 'email', required: true },
                        { name: 'Tax ID Number', type: 'text', required: true, maxLength: 50 }
                    ]
                },
                {
                    title: 'Requisition Details',
                    fields: [
                        { name: 'PO Number', type: 'text', required: true, autoGenerated: true },
                        { name: 'Requisition Date', type: 'date', required: true, defaultValue: 'today' },
                        { name: 'Required Delivery Date', type: 'date', required: true },
                        {
                            name: 'Delivery Location', type: 'select', required: true,
                            options: ['Main Office - Sfax', 'Branch Office - Tunis', 'Warehouse 1', 'Warehouse 2']
                        },
                        {
                            name: 'Requesting Department', type: 'select', required: true,
                            options: ['Sales', 'Operations', 'Finance', 'HR', 'Admin']
                        },
                        { name: 'Requested By', type: 'text', required: true },
                        { name: 'Employee ID', type: 'text', required: true }
                    ]
                },
                {
                    title: 'Line Items',
                    type: 'repeatable',
                    fields: [
                        { name: 'Item No.', type: 'number', required: true },
                        { name: 'Product Code', type: 'text', required: true },
                        { name: 'Product Description', type: 'textarea', required: true, maxLength: 500 },
                        {
                            name: 'Unit of Measure', type: 'select', required: true,
                            options: ['PCS', 'BOX', 'KG', 'LITER', 'METER', 'SET', 'UNIT']
                        },
                        { name: 'Quantity', type: 'number', required: true, min: 1 },
                        { name: 'Unit Price (TND)', type: 'currency', required: true, currency: 'TND' },
                        { name: 'Discount %', type: 'number', min: 0, max: 100 },
                        { name: 'Tax Rate %', type: 'number', required: true, defaultValue: 19 },
                        {
                            name: 'Line Total', type: 'currency', calculated: true, readOnly: true,
                            formula: '(Quantity * Unit Price * (1 - Discount/100)) * (1 + Tax Rate/100)'
                        }
                    ]
                },
                {
                    title: 'Financial Summary',
                    fields: [
                        { name: 'Subtotal (Before Tax)', type: 'currency', calculated: true, readOnly: true },
                        { name: 'Total Discount', type: 'currency', calculated: true, readOnly: true },
                        { name: 'Total Tax (TVA)', type: 'currency', calculated: true, readOnly: true },
                        { name: 'Shipping Cost', type: 'currency', required: false },
                        { name: 'Other Charges', type: 'currency', required: false },
                        { name: 'Grand Total', type: 'currency', calculated: true, readOnly: true }
                    ]
                },
                {
                    title: 'Terms and Conditions',
                    fields: [
                        {
                            name: 'Payment Terms', type: 'select', required: true,
                            options: ['Cash on Delivery', 'Net 15', 'Net 30', 'Net 60', '50% Advance + 50% on Delivery', 'Net 90']
                        },
                        {
                            name: 'Delivery Terms', type: 'select', required: true,
                            options: ['FOB', 'CIF', 'EXW', 'DDP', 'DAP']
                        },
                        { name: 'Warranty Period', type: 'text', required: false },
                        { name: 'Special Instructions', type: 'textarea', required: false, maxLength: 500 }
                    ]
                },
                {
                    title: 'Approvals',
                    type: 'workflow',
                    approvers: [
                        { role: 'Department Manager', condition: 'amount > 1000', required: true },
                        { role: 'Finance Manager', condition: 'amount > 5000', required: true },
                        { role: 'General Manager', condition: 'amount > 20000', required: true }
                    ],
                    fields: [
                        { name: 'Requested By Signature', type: 'signature', required: true },
                        { name: 'Department Manager Approval', type: 'signature', required: 'conditional' },
                        { name: 'Finance Manager Approval', type: 'signature', required: 'conditional' },
                        { name: 'General Manager Approval', type: 'signature', required: 'conditional' },
                        { name: 'Approval Date', type: 'date', autoFill: true }
                    ]
                }
            ]
        },

        instructions: [
            'Complete all required fields marked with asterisk (*)',
            'Ensure vendor information matches our approved vendor database',
            'Product codes must be validated against inventory system',
            'Obtain proper approvals based on total amount thresholds',
            'Attach supporting quotations if amount exceeds 5,000 TND',
            'Submit completed form to Finance Department within 24 hours',
            'Retain copy for department records',
            'Original will be filed in Finance Department after processing'
        ],

        validationRules: [
            'Required delivery date must be at least 3 business days from request date',
            'All line items must have valid product codes',
            'Total amount must not exceed department monthly budget',
            'Vendor must be in approved vendor list',
            'Tax rate must match current regulatory requirements (19% TVA in Tunisia)'
        ],

        relatedDocuments: [
            'Vendor Registration Form',
            'Budget Approval Form',
            'Goods Receipt Note',
            'Invoice Processing Procedure',
            'Money & Finance Playbook'
        ]
    },

    {
        id: 'FIN-002',
        title: 'Expense Reimbursement Form',
        department: 'Finance',
        category: 'Employee Expenses',
        version: '1.8',
        effectiveDate: '2024-01-15',
        approvedBy: 'Finance Manager',
        description: 'Form for employee expense claims and reimbursements for business-related expenses',

        formStructure: {
            sections: [
                {
                    title: 'Employee Information',
                    fields: [
                        { name: 'Employee Name', type: 'text', required: true },
                        { name: 'Employee ID', type: 'text', required: true },
                        {
                            name: 'Department', type: 'select', required: true,
                            options: ['Sales', 'Operations', 'Finance', 'HR', 'IT', 'Admin']
                        },
                        { name: 'Position', type: 'text', required: true },
                        { name: 'Bank Account Number (IBAN)', type: 'text', required: true }
                    ]
                },
                {
                    title: 'Expense Details',
                    type: 'repeatable',
                    fields: [
                        { name: 'Date of Expense', type: 'date', required: true },
                        {
                            name: 'Expense Category', type: 'select', required: true,
                            options: ['Transportation', 'Accommodation', 'Meals', 'Communication',
                                'Office Supplies', 'Client Entertainment', 'Training', 'Other']
                        },
                        { name: 'Description', type: 'textarea', required: true, maxLength: 200 },
                        { name: 'Amount (TND)', type: 'currency', required: true, currency: 'TND' },
                        { name: 'Receipt Number', type: 'text', required: true },
                        { name: 'Receipt Attached', type: 'checkbox', required: true },
                        { name: 'Business Purpose', type: 'textarea', required: true, maxLength: 300 }
                    ]
                },
                {
                    title: 'Summary',
                    fields: [
                        { name: 'Total Expenses', type: 'currency', calculated: true, readOnly: true },
                        { name: 'Advance Received', type: 'currency', required: false },
                        { name: 'Amount to be Reimbursed', type: 'currency', calculated: true, readOnly: true }
                    ]
                },
                {
                    title: 'Certification',
                    fields: [
                        { name: 'I certify all expenses are accurate', type: 'checkbox', required: true },
                        { name: 'Employee Signature', type: 'signature', required: true },
                        { name: 'Submission Date', type: 'date', required: true },
                        { name: 'Manager Approval', type: 'signature', required: true },
                        { name: 'Finance Approval', type: 'signature', required: true }
                    ]
                }
            ]
        },

        instructions: [
            'Submit expense claims within 30 days of expense date',
            'Attach original receipts for all expenses over 20 TND',
            'Receipts must be legible and show VAT details',
            'Per diem rates apply for meals - check policy limits',
            'Manager approval required before submission to Finance',
            'Reimbursement processed within 14 business days of approval',
            'Claims over 500 TND require additional documentation'
        ],

        policyLimits: {
            'Transportation': { dailyLimit: 50, requiresReceipt: true },
            'Meals': { perMeal: 15, dailyLimit: 40, requiresReceipt: false },
            'Accommodation': { perNight: 150, requiresReceipt: true },
            'Client Entertainment': { perEvent: 200, requiresApproval: true, requiresReceipt: true }
        },

        validationRules: [
            'Expenses must be submitted within 30 days',
            'Manager approval required for all claims',
            'Receipts required for expenses over 20 TND',
            'Policy limits must not be exceeded without prior approval'
        ],

        relatedDocuments: [
            'Expense Policy',
            'Travel Policy',
            'Money & Finance Playbook',
            'People & Admin Playbook'
        ]
    },

    {
        id: 'FIN-003',
        title: 'Invoice Processing Form',
        department: 'Finance',
        category: 'Accounts Payable',
        version: '2.0',
        effectiveDate: '2024-01-15',
        approvedBy: 'Finance Manager',
        description: 'Standard form for processing supplier invoices and ensuring proper payment authorization',

        formStructure: {
            sections: [
                {
                    title: 'Invoice Information',
                    fields: [
                        { name: 'Invoice Number', type: 'text', required: true },
                        { name: 'Invoice Date', type: 'date', required: true },
                        { name: 'Supplier Name', type: 'text', required: true },
                        { name: 'Supplier Code', type: 'text', required: true },
                        { name: 'Purchase Order Number', type: 'text', required: true },
                        { name: 'Goods Receipt Note Number', type: 'text', required: false }
                    ]
                },
                {
                    title: 'Invoice Details',
                    fields: [
                        { name: 'Description', type: 'textarea', required: true, maxLength: 500 },
                        { name: 'Subtotal (Before Tax)', type: 'currency', required: true, currency: 'TND' },
                        { name: 'TVA Amount', type: 'currency', required: true, currency: 'TND' },
                        { name: 'Other Charges', type: 'currency', required: false, currency: 'TND' },
                        { name: 'Total Amount', type: 'currency', calculated: true, readOnly: true }
                    ]
                },
                {
                    title: 'Payment Details',
                    fields: [
                        {
                            name: 'Payment Terms', type: 'select', required: true,
                            options: ['Cash', 'Net 15', 'Net 30', 'Net 60', 'Net 90']
                        },
                        { name: 'Due Date', type: 'date', calculated: true, readOnly: true },
                        {
                            name: 'Payment Method', type: 'select', required: true,
                            options: ['Bank Transfer', 'Check', 'Cash']
                        },
                        { name: 'Early Payment Discount Available', type: 'checkbox' },
                        { name: 'Discount Percentage', type: 'number', min: 0, max: 10 }
                    ]
                },
                {
                    title: 'Verification',
                    fields: [
                        { name: 'Invoice matches PO', type: 'checkbox', required: true },
                        { name: 'Goods/Services received', type: 'checkbox', required: true },
                        { name: 'Pricing correct', type: 'checkbox', required: true },
                        { name: 'Calculations verified', type: 'checkbox', required: true },
                        { name: 'Budget available', type: 'checkbox', required: true }
                    ]
                },
                {
                    title: 'Approvals',
                    type: 'workflow',
                    fields: [
                        { name: 'Verified By', type: 'text', required: true },
                        { name: 'Verifier Signature', type: 'signature', required: true },
                        { name: 'Manager Approval', type: 'signature', required: true },
                        { name: 'Finance Authorization', type: 'signature', required: true },
                        { name: 'Payment Processed By', type: 'text' },
                        { name: 'Payment Date', type: 'date' }
                    ]
                }
            ]
        },

        instructions: [
            'Match invoice to purchase order before processing',
            'Verify goods/services have been received',
            'Check all calculations and pricing',
            'Ensure budget code is correct and funds available',
            'Obtain all required approvals before payment',
            'Process payment according to terms to capture discounts',
            'File invoice with supporting documents after payment'
        ],

        validationRules: [
            'Invoice must be matched to an approved purchase order',
            'Supplier must be in approved vendor list',
            'Invoice amount must match PO within acceptable tolerance (5%)',
            'All supporting documents must be attached',
            'Payment must be within budget authorization'
        ],

        relatedDocuments: [
            'Purchase Order Form',
            'Goods Receipt Note',
            'Payment Authorization Procedure',
            'Money & Finance Playbook'
        ]
    },

    {
        id: 'FIN-004',
        title: 'Budget Request Form',
        department: 'Finance',
        category: 'Budget Management',
        version: '1.5',
        effectiveDate: '2024-01-15',
        description: 'Form for requesting budget allocation or additional funds for departmental activities',

        formStructure: {
            sections: [
                {
                    title: 'Request Information',
                    fields: [
                        { name: 'Request Number', type: 'text', autoGenerated: true },
                        { name: 'Request Date', type: 'date', required: true, defaultValue: 'today' },
                        {
                            name: 'Department', type: 'select', required: true,
                            options: ['Sales', 'Operations', 'Finance', 'HR', 'Admin']
                        },
                        { name: 'Requested By', type: 'text', required: true },
                        {
                            name: 'Budget Period', type: 'select', required: true,
                            options: ['Q1 2024', 'Q2 2024', 'Q3 2024', 'Q4 2024', 'Annual 2024']
                        }
                    ]
                },
                {
                    title: 'Budget Details',
                    type: 'repeatable',
                    fields: [
                        { name: 'Item/Activity', type: 'text', required: true },
                        {
                            name: 'Category', type: 'select', required: true,
                            options: ['Personnel', 'Equipment', 'Supplies', 'Travel', 'Training', 'Marketing', 'Other']
                        },
                        { name: 'Description', type: 'textarea', required: true, maxLength: 500 },
                        { name: 'Quantity', type: 'number', required: true },
                        { name: 'Unit Cost', type: 'currency', required: true, currency: 'TND' },
                        { name: 'Total Cost', type: 'currency', calculated: true, readOnly: true }
                    ]
                },
                {
                    title: 'Justification',
                    fields: [
                        { name: 'Business Justification', type: 'textarea', required: true, maxLength: 1000 },
                        { name: 'Expected Benefits', type: 'textarea', required: true, maxLength: 500 },
                        { name: 'Impact if Not Approved', type: 'textarea', required: true, maxLength: 500 },
                        { name: 'Alternative Options Considered', type: 'textarea', maxLength: 500 }
                    ]
                },
                {
                    title: 'Summary',
                    fields: [
                        { name: 'Total Budget Requested', type: 'currency', calculated: true, readOnly: true },
                        { name: 'Current Budget Available', type: 'currency', required: true },
                        { name: 'Additional Funding Required', type: 'currency', calculated: true, readOnly: true }
                    ]
                },
                {
                    title: 'Approvals',
                    type: 'workflow',
                    fields: [
                        { name: 'Department Manager Approval', type: 'signature', required: true },
                        { name: 'Finance Manager Review', type: 'signature', required: true },
                        { name: 'General Manager Authorization', type: 'signature', required: true },
                        { name: 'Approval Date', type: 'date', autoFill: true }
                    ]
                }
            ]
        },

        instructions: [
            'Submit budget requests at least 30 days before budget period starts',
            'Provide detailed justification for each budget item',
            'Include supporting documentation (quotes, proposals)',
            'Demonstrate business value and expected ROI',
            'Department manager must review before submission',
            'Finance will review against overall budget constraints',
            'Final approval by General Manager for amounts over 10,000 TND'
        ],

        validationRules: [
            'Request must be submitted 30 days in advance',
            'All line items must have clear justification',
            'Total request must be within departmental limits',
            'Supporting documentation required for items over 5,000 TND'
        ]
    },

    {
        id: 'FIN-005',
        title: 'Payment Authorization Form',
        department: 'Finance',
        category: 'Cash Management',
        version: '1.9',
        effectiveDate: '2024-01-15',
        description: 'Authorization form for processing payments to suppliers, contractors, and service providers',

        formStructure: {
            sections: [
                {
                    title: 'Payment Information',
                    fields: [
                        { name: 'Payment Request Number', type: 'text', autoGenerated: true },
                        { name: 'Request Date', type: 'date', required: true, defaultValue: 'today' },
                        { name: 'Payee Name', type: 'text', required: true },
                        {
                            name: 'Payee Type', type: 'select', required: true,
                            options: ['Supplier', 'Contractor', 'Employee', 'Service Provider', 'Utility', 'Tax Authority', 'Other']
                        },
                        { name: 'Payment Amount (TND)', type: 'currency', required: true, currency: 'TND' }
                    ]
                },
                {
                    title: 'Payment Method',
                    fields: [
                        {
                            name: 'Payment Method', type: 'select', required: true,
                            options: ['Bank Transfer', 'Check', 'Cash', 'Credit Card']
                        },
                        { name: 'Bank Account Number (if transfer)', type: 'text' },
                        { name: 'Bank Name', type: 'text' },
                        { name: 'Payment Date', type: 'date', required: true }
                    ]
                },
                {
                    title: 'Payment Purpose',
                    fields: [
                        { name: 'Invoice/Reference Number', type: 'text', required: true },
                        { name: 'Description of Payment', type: 'textarea', required: true, maxLength: 500 },
                        {
                            name: 'Cost Center', type: 'select', required: true,
                            options: ['Sales', 'Operations', 'Admin', 'General']
                        },
                        { name: 'Budget Code', type: 'text', required: true }
                    ]
                },
                {
                    title: 'Supporting Documents',
                    fields: [
                        { name: 'Invoice Attached', type: 'checkbox', required: true },
                        { name: 'Purchase Order Attached', type: 'checkbox' },
                        { name: 'Delivery Note Attached', type: 'checkbox' },
                        { name: 'Contract Attached', type: 'checkbox' },
                        { name: 'Other Documents', type: 'text' }
                    ]
                },
                {
                    title: 'Approvals',
                    type: 'workflow',
                    approvers: [
                        { role: 'Department Manager', condition: 'amount > 500', required: true },
                        { role: 'Finance Manager', condition: 'amount > 5000', required: true },
                        { role: 'General Manager', condition: 'amount > 20000', required: true }
                    ],
                    fields: [
                        { name: 'Requested By', type: 'text', required: true },
                        { name: 'Requester Signature', type: 'signature', required: true },
                        { name: 'Manager Approval', type: 'signature', required: 'conditional' },
                        { name: 'Finance Approval', type: 'signature', required: 'conditional' },
                        { name: 'GM Authorization', type: 'signature', required: 'conditional' },
                        { name: 'Payment Processed By', type: 'text' },
                        { name: 'Payment Completion Date', type: 'date' }
                    ]
                }
            ]
        },

        instructions: [
            'Ensure all supporting documents are attached',
            'Verify payee information is correct',
            'Check budget availability before requesting approval',
            'Obtain approvals based on amount thresholds',
            'Submit to Finance at least 3 days before required payment date',
            'For urgent payments, mark as urgent and contact Finance',
            'Retain copy of authorization for records'
        ],

        validationRules: [
            'Payment amount must match invoice/supporting documents',
            'All required approvals must be obtained',
            'Budget must have sufficient funds',
            'Payee must be registered in system',
            'Bank details must be verified for transfers'
        ]
    },

    {
        id: 'FIN-006',
        title: 'Petty Cash Voucher',
        department: 'Finance',
        category: 'Cash Management',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Voucher for petty cash disbursements and replenishment',
        formStructure: {
            sections: [
                { title: 'Voucher Details', fields: [
                    { name: 'Voucher Number', type: 'text', autoGenerated: true },
                    { name: 'Date', type: 'date', required: true, defaultValue: 'today' },
                    { name: 'Requested By', type: 'text', required: true },
                    { name: 'Department', type: 'select', required: true, options: ['Sales', 'Operations', 'Admin', 'Finance'] },
                    { name: 'Amount (TND)', type: 'currency', required: true, currency: 'TND' }
                ]},
                { title: 'Purpose', fields: [
                    { name: 'Purpose of Expense', type: 'textarea', required: true, maxLength: 300 },
                    { name: 'Receipt Attached', type: 'checkbox', required: true }
                ]},
                { title: 'Approval', fields: [
                    { name: 'Authorized By', type: 'text', required: true },
                    { name: 'Signature', type: 'signature', required: true },
                    { name: 'Custodian Signature', type: 'signature', required: true }
                ]}
            ]
        },
        instructions: ['Obtain receipt for all petty cash disbursements', 'Submit voucher within 24 hours', 'Maximum single disbursement per policy'],
        relatedDocuments: ['Money & Finance Playbook', 'Expense Policy']
    },
    {
        id: 'FIN-007',
        title: 'Vendor Registration Form',
        department: 'Finance',
        category: 'Procurement',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Form to register new vendors and suppliers',
        formStructure: {
            sections: [
                { title: 'Vendor Information', fields: [
                    { name: 'Legal Name', type: 'text', required: true },
                    { name: 'Trade Name', type: 'text' },
                    { name: 'Tax ID / Registration', type: 'text', required: true },
                    { name: 'Address', type: 'textarea', required: true },
                    { name: 'Phone', type: 'tel', required: true },
                    { name: 'Email', type: 'email', required: true },
                    { name: 'Website', type: 'text' }
                ]},
                { title: 'Bank Details', fields: [
                    { name: 'Bank Name', type: 'text', required: true },
                    { name: 'Account Number', type: 'text', required: true },
                    { name: 'IBAN', type: 'text' },
                    { name: 'SWIFT/BIC', type: 'text' }
                ]},
                { title: 'Contact Person', fields: [
                    { name: 'Contact Name', type: 'text', required: true },
                    { name: 'Position', type: 'text' },
                    { name: 'Phone', type: 'tel' },
                    { name: 'Email', type: 'email', required: true }
                ]},
                { title: 'Products/Services', fields: [
                    { name: 'Product or Service Category', type: 'select', required: true, options: ['Fire Equipment', 'PPE', 'Workwear', 'Signage', 'Consumables', 'Services', 'Other'] },
                    { name: 'Description', type: 'textarea', required: true }
                ]},
                { title: 'Approval', fields: [
                    { name: 'Submitted By', type: 'text', required: true },
                    { name: 'Signature', type: 'signature', required: true },
                    { name: 'Finance Approval', type: 'signature', required: true }
                ]}
            ]
        },
        instructions: ['Attach tax registration certificate', 'Verify bank details before payment', 'Review annually'],
        relatedDocuments: ['Purchase Order Form', 'Money & Finance Playbook']
    },
    {
        id: 'FIN-008',
        title: 'Credit Note Request',
        department: 'Finance',
        category: 'Revenue',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Request form for issuing credit notes to customers',
        formStructure: {
            sections: [
                { title: 'Request Details', fields: [
                    { name: 'Request Number', type: 'text', autoGenerated: true },
                    { name: 'Date', type: 'date', required: true, defaultValue: 'today' },
                    { name: 'Requested By', type: 'text', required: true },
                    { name: 'Customer Name', type: 'text', required: true },
                    { name: 'Original Invoice Number', type: 'text', required: true },
                    { name: 'Original Invoice Date', type: 'date', required: true },
                    { name: 'Credit Amount (TND)', type: 'currency', required: true, currency: 'TND' }
                ]},
                { title: 'Reason', fields: [
                    { name: 'Reason for Credit', type: 'select', required: true, options: ['Returned Goods', 'Billing Error', 'Service Deficiency', 'Discount Adjustment', 'Other'] },
                    { name: 'Description', type: 'textarea', required: true, maxLength: 500 }
                ]},
                { title: 'Approval', fields: [
                    { name: 'Sales Responsible Approval', type: 'signature', required: true },
                    { name: 'Finance Approval', type: 'signature', required: true },
                    { name: 'Manager Approval', type: 'signature', required: 'conditional' }
                ]}
            ]
        },
        instructions: ['Attach supporting documentation', 'Obtain approval per authority matrix', 'Process within 5 business days'],
        relatedDocuments: ['Money & Finance Playbook', 'Warranty & Returns Policy']
    },
    {
        id: 'FIN-009',
        title: 'Financial Report Template',
        department: 'Finance',
        category: 'Reporting',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Template for periodic financial reports',
        formStructure: {
            sections: [
                { title: 'Report Period', fields: [
                    { name: 'Report Type', type: 'select', required: true, options: ['Monthly', 'Quarterly', 'Annual'] },
                    { name: 'Period Start', type: 'date', required: true },
                    { name: 'Period End', type: 'date', required: true },
                    { name: 'Prepared By', type: 'text', required: true },
                    { name: 'Date Prepared', type: 'date', required: true, defaultValue: 'today' }
                ]},
                { title: 'Summary', fields: [
                    { name: 'Revenue (TND)', type: 'currency', required: true, currency: 'TND' },
                    { name: 'Expenses (TND)', type: 'currency', required: true, currency: 'TND' },
                    { name: 'Net Result (TND)', type: 'currency', required: true, currency: 'TND' },
                    { name: 'Key Highlights', type: 'textarea', required: true },
                    { name: 'Risks or Concerns', type: 'textarea' }
                ]},
                { title: 'Approval', fields: [
                    { name: 'Finance Responsible Signature', type: 'signature', required: true },
                    { name: 'Manager Review', type: 'signature', required: true }
                ]}
            ]
        },
        instructions: ['Submit by 5th working day of following period', 'Include variance analysis', 'Distribute to management'],
        relatedDocuments: ['Money & Finance Playbook', 'Budget Approval Form']
    },
    {
        id: 'FIN-010',
        title: 'Cash Receipt Voucher',
        department: 'Finance',
        category: 'Cash Management',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Voucher for recording cash receipts',
        formStructure: {
            sections: [
                { title: 'Receipt Details', fields: [
                    { name: 'Voucher Number', type: 'text', autoGenerated: true },
                    { name: 'Date', type: 'date', required: true, defaultValue: 'today' },
                    { name: 'Received From', type: 'text', required: true },
                    { name: 'Amount (TND)', type: 'currency', required: true, currency: 'TND' },
                    { name: 'Payment Method', type: 'select', required: true, options: ['Cash', 'Check', 'Bank Transfer', 'Other'] }
                ]},
                { title: 'Purpose', fields: [
                    { name: 'Purpose', type: 'select', required: true, options: ['Customer Payment', 'Advance', 'Reimbursement', 'Other'] },
                    { name: 'Invoice/Reference Number', type: 'text' },
                    { name: 'Remarks', type: 'textarea' }
                ]},
                { title: 'Acknowledgement', fields: [
                    { name: 'Received By', type: 'text', required: true },
                    { name: 'Signature', type: 'signature', required: true },
                    { name: 'Payer Signature', type: 'signature', required: true }
                ]}
            ]
        },
        instructions: ['Issue duplicate copy to payer', 'Record in cash book same day', 'Deposit cash within 24 hours'],
        relatedDocuments: ['Money & Finance Playbook', 'Payment Authorization Form']
    }
];
