import { ManagementRecord } from '../../types/records';

export const qualityRecords: ManagementRecord[] = [
    {
        id: 'QA-001',
        title: 'Customer Complaint Investigation',
        department: 'Quality',
        category: 'Complaints',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Form to document and investigate customer complaints',
        formStructure: {
            sections: [
                { title: 'Complaint', fields: [
                    { name: 'Complaint Reference', type: 'text', autoGenerated: true },
                    { name: 'Date Received', type: 'date', required: true },
                    { name: 'Received By', type: 'text', required: true },
                    { name: 'Customer Name', type: 'text', required: true },
                    { name: 'Contact', type: 'text', required: true },
                    { name: 'Complaint Category', type: 'select', required: true, options: ['Service', 'Product', 'Billing', 'Conduct', 'Other'] },
                    { name: 'Description', type: 'textarea', required: true, maxLength: 1000 }
                ]},
                { title: 'Investigation', fields: [
                    { name: 'Assigned To', type: 'text', required: true },
                    { name: 'Investigation Summary', type: 'textarea', required: true },
                    { name: 'Root Cause', type: 'textarea', required: true },
                    { name: 'Evidence / Records Reviewed', type: 'textarea' }
                ]},
                { title: 'Resolution', fields: [
                    { name: 'Resolution', type: 'select', required: true, options: ['Rework', 'Credit', 'Replacement', 'Apology', 'Other'] },
                    { name: 'Details', type: 'textarea', required: true },
                    { name: 'Customer Notified', type: 'checkbox', required: true },
                    { name: 'Date Closed', type: 'date', required: true }
                ]},
                { title: 'Sign-off', fields: [
                    { name: 'Investigator Signature', type: 'signature', required: true },
                    { name: 'Manager Review', type: 'signature', required: true }
                ]}
            ]
        },
        instructions: ['Acknowledge within 4 hours', 'Investigate within 24 hours', 'Resolve per complaint handling process'],
        relatedDocuments: ['Company Manual', 'Complaint Handling Process', 'Sales & Customer Playbook']
    },
    {
        id: 'QA-002',
        title: 'Corrective Action Request',
        department: 'Quality',
        category: 'Improvement',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Request for corrective action following non-conformance or incident',
        formStructure: {
            sections: [
                { title: 'Issue', fields: [
                    { name: 'CAR Number', type: 'text', autoGenerated: true },
                    { name: 'Date', type: 'date', required: true, defaultValue: 'today' },
                    { name: 'Raised By', type: 'text', required: true },
                    { name: 'Department', type: 'text', required: true },
                    { name: 'Description of Non-conformance', type: 'textarea', required: true, maxLength: 1000 },
                    { name: 'Related Complaint / NCR', type: 'text' }
                ]},
                { title: 'Action', fields: [
                    { name: 'Assigned To', type: 'text', required: true },
                    { name: 'Corrective Action', type: 'textarea', required: true },
                    { name: 'Due Date', type: 'date', required: true },
                    { name: 'Completed Date', type: 'date' },
                    { name: 'Verification', type: 'textarea' }
                ]},
                { title: 'Closure', fields: [
                    { name: 'Action Effective', type: 'checkbox', required: true },
                    { name: 'Closed By', type: 'text' },
                    { name: 'Manager Signature', type: 'signature', required: true }
                ]}
            ]
        },
        instructions: ['Complete root cause analysis', 'Define and implement action', 'Verify effectiveness'],
        relatedDocuments: ['Company Manual', 'Quality Procedures', 'Non-Conformance Report']
    },
    {
        id: 'QA-003',
        title: 'Internal Audit Checklist',
        department: 'Quality',
        category: 'Audit',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Checklist for internal process and quality audits',
        formStructure: {
            sections: [
                { title: 'Audit Details', fields: [
                    { name: 'Audit Reference', type: 'text', autoGenerated: true },
                    { name: 'Date', type: 'date', required: true },
                    { name: 'Auditor(s)', type: 'text', required: true },
                    { name: 'Area / Process', type: 'text', required: true },
                    { name: 'Scope', type: 'textarea', required: true }
                ]},
                { title: 'Checklist', type: 'repeatable', fields: [
                    { name: 'Criteria / Requirement', type: 'text', required: true },
                    { name: 'Finding', type: 'select', required: true, options: ['Conform', 'Non-conform', 'Observation', 'N/A'] },
                    { name: 'Evidence', type: 'textarea' },
                    { name: 'Notes', type: 'textarea' }
                ]},
                { title: 'Summary', fields: [
                    { name: 'Overall Result', type: 'select', required: true, options: ['Pass', 'Pass with Observations', 'Fail'] },
                    { name: 'Non-conformances', type: 'textarea' },
                    { name: 'Observations', type: 'textarea' },
                    { name: 'Auditor Signature', type: 'signature', required: true },
                    { name: 'Auditee Acknowledgement', type: 'signature', required: true }
                ]}
            ]
        },
        instructions: ['Schedule per audit plan', 'Document evidence', 'Follow up on non-conformances'],
        relatedDocuments: ['Company Manual', 'Quality Procedures', 'Corrective Action Request']
    },
    {
        id: 'QA-004',
        title: 'Supplier Audit Form',
        department: 'Quality',
        category: 'Audit',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Form for auditing supplier quality and compliance',
        formStructure: {
            sections: [
                { title: 'Audit Details', fields: [
                    { name: 'Audit Reference', type: 'text', autoGenerated: true },
                    { name: 'Date', type: 'date', required: true },
                    { name: 'Auditor(s)', type: 'text', required: true },
                    { name: 'Supplier Name', type: 'text', required: true },
                    { name: 'Location', type: 'text', required: true },
                    { name: 'Scope', type: 'textarea', required: true }
                ]},
                { title: 'Assessment', type: 'repeatable', fields: [
                    { name: 'Criteria', type: 'text', required: true },
                    { name: 'Score', type: 'rating', scale: '1-5' },
                    { name: 'Comments', type: 'textarea' }
                ]},
                { title: 'Result', fields: [
                    { name: 'Overall Score', type: 'number', required: true },
                    { name: 'Recommendation', type: 'select', required: true, options: ['Approve', 'Approve with Conditions', 'Reject', 'Re-audit'] },
                    { name: 'Findings', type: 'textarea', required: true },
                    { name: 'Auditor Signature', type: 'signature', required: true },
                    { name: 'Supplier Representative', type: 'text' },
                    { name: 'Supplier Signature', type: 'signature' }
                ]}
            ]
        },
        instructions: ['Conduct per supplier audit plan', 'Document evidence', 'Update supplier qualification'],
        relatedDocuments: ['Products & Inventory Playbook', 'Vendor Registration', 'Supplier Performance Evaluation']
    },
    {
        id: 'QA-005',
        title: 'Quality Metrics Dashboard',
        department: 'Quality',
        category: 'Reporting',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Template for periodic quality metrics reporting',
        formStructure: {
            sections: [
                { title: 'Period', fields: [
                    { name: 'Report Period', type: 'select', required: true, options: ['Monthly', 'Quarterly', 'Annual'] },
                    { name: 'Period Start', type: 'date', required: true },
                    { name: 'Period End', type: 'date', required: true },
                    { name: 'Prepared By', type: 'text', required: true },
                    { name: 'Date', type: 'date', required: true, defaultValue: 'today' }
                ]},
                { title: 'Metrics', fields: [
                    { name: 'Customer Complaints', type: 'number', required: true },
                    { name: 'Complaints Resolved in Time', type: 'number', required: true },
                    { name: 'NCRs Raised', type: 'number', required: true },
                    { name: 'CARs Closed', type: 'number', required: true },
                    { name: 'Internal Audits', type: 'number', required: true },
                    { name: 'Supplier Audits', type: 'number' },
                    { name: 'Key Highlights', type: 'textarea', required: true },
                    { name: 'Risks / Trends', type: 'textarea' }
                ]},
                { title: 'Approval', fields: [
                    { name: 'Responsible Signature', type: 'signature', required: true },
                    { name: 'Manager Review', type: 'signature', required: true }
                ]}
            ]
        },
        instructions: ['Submit by 5th working day of following period', 'Review trends', 'Present to management'],
        relatedDocuments: ['Company Manual', 'Quality Procedures', 'Internal Audit Checklist']
    }
];
