import { ManagementRecord } from '../../types/records';

export const salesRecords: ManagementRecord[] = [
    {
        id: 'SALES-001',
        title: 'Customer Quotation Form',
        department: 'Sales',
        category: 'Sales Process',
        version: '2.3',
        effectiveDate: '2024-01-15',
        description: 'Standard quotation form for providing price quotes to customers for fire safety equipment and services',

        formStructure: {
            sections: [
                {
                    title: 'Customer Information',
                    fields: [
                        { name: 'Customer Name', type: 'text', required: true },
                        { name: 'Customer Code', type: 'text' },
                        { name: 'Contact Person', type: 'text', required: true },
                        { name: 'Phone', type: 'tel', required: true },
                        { name: 'Email', type: 'email', required: true },
                        { name: 'Address', type: 'textarea', required: true },
                        {
                            name: 'Customer Type', type: 'select', required: true,
                            options: ['New Customer', 'Existing Customer', 'Government', 'Corporate', 'Individual']
                        }
                    ]
                },
                {
                    title: 'Quotation Details',
                    fields: [
                        { name: 'Quotation Number', type: 'text', autoGenerated: true, required: true },
                        { name: 'Date', type: 'date', required: true, defaultValue: 'today' },
                        { name: 'Valid Until', type: 'date', required: true },
                        { name: 'Sales Representative', type: 'text', required: true },
                        { name: 'Reference/Inquiry Number', type: 'text' }
                    ]
                },
                {
                    title: 'Items Quoted',
                    type: 'repeatable',
                    fields: [
                        { name: 'Item No.', type: 'number', required: true },
                        { name: 'Product/Service Code', type: 'text', required: true },
                        { name: 'Description', type: 'textarea', required: true },
                        { name: 'Quantity', type: 'number', required: true, min: 1 },
                        {
                            name: 'Unit', type: 'select', required: true,
                            options: ['PCS', 'SET', 'SERVICE', 'KG', 'LITER', 'METER']
                        },
                        { name: 'Unit Price (TND)', type: 'currency', required: true, currency: 'TND' },
                        { name: 'Discount %', type: 'number', min: 0, max: 20 },
                        { name: 'Line Total', type: 'currency', calculated: true, readOnly: true }
                    ]
                },
                {
                    title: 'Pricing Summary',
                    fields: [
                        { name: 'Subtotal', type: 'currency', calculated: true, readOnly: true, currency: 'TND' },
                        { name: 'Discount', type: 'currency', calculated: true, readOnly: true, currency: 'TND' },
                        { name: 'Subtotal After Discount', type: 'currency', calculated: true, readOnly: true },
                        { name: 'TVA 19%', type: 'currency', calculated: true, readOnly: true, currency: 'TND' },
                        { name: 'Travel Fees (if applicable)', type: 'currency', currency: 'TND' },
                        { name: 'Total Amount', type: 'currency', calculated: true, readOnly: true, currency: 'TND' }
                    ]
                },
                {
                    title: 'Terms & Conditions',
                    fields: [
                        {
                            name: 'Payment Terms', type: 'select', required: true,
                            options: ['Cash on Delivery', 'Net 30', 'Net 60', '50% Advance', 'Net 90']
                        },
                        { name: 'Delivery Timeline', type: 'text', required: true },
                        { name: 'Warranty Period', type: 'text', required: true },
                        { name: 'Special Conditions', type: 'textarea' }
                    ]
                },
                {
                    title: 'Approval',
                    fields: [
                        { name: 'Prepared By', type: 'text', required: true },
                        { name: 'Sales Rep Signature', type: 'signature', required: true },
                        { name: 'Approved By (if discount >15%)', type: 'text' },
                        { name: 'Manager Signature', type: 'signature', required: 'conditional' }
                    ]
                }
            ]
        },

        instructions: [
            'Use current price list for  all products and services',
            'Discounts up to 15% can be approved by sales representative',
            'Discounts above 15% require sales manager approval',
            'Quotation valid for 30 days unless otherwise specified',
            'Include travel fees for locations beyond 120km from Sfax/Tunis',
            'Provide customer with signed and stamped copy',
            'Follow up within 3 days of quotation delivery'
        ],

        validationRules: [
            'All prices must match current approved price list',
            'Discounts must be within authorized limits',
            'Required margin must be maintained',
            'Customer information must be complete and verified'
        ],

        relatedDocuments: [
            'Sales & Customer Playbook',
            'Current Price List',
            'Discount Authorization Matrix',
            'Company Manual'
        ]
    },

    {
        id: 'SALES-002',
        title: 'Sales Order Form',
        department: 'Sales',
        category: 'Order Processing',
        version: '2.1',
        effectiveDate: '2024-01-15',
        description: 'Official sales order form for confirming customer orders and initiating delivery process',

        formStructure: {
            sections: [
                {
                    title: 'Order Information',
                    fields: [
                        { name: 'Sales Order Number', type: 'text', autoGenerated: true, required: true },
                        { name: 'Order Date', type: 'date', required: true, defaultValue: 'today' },
                        { name: 'Quotation Reference', type: 'text', required: true },
                        { name: 'Customer PO Number', type: 'text' },
                        { name: 'Expected Delivery Date', type: 'date', required: true }
                    ]
                },
                {
                    title: 'Customer Details',
                    fields: [
                        { name: 'Customer Name', type: 'text', required: true },
                        { name: 'Customer Code', type: 'text', required: true },
                        { name: 'Delivery Address', type: 'textarea', required: true },
                        { name: 'Contact Person', type: 'text', required: true },
                        { name: 'Phone', type: 'tel', required: true }
                    ]
                },
                {
                    title: 'Order Items',
                    type: 'repeatable',
                    fields: [
                        { name: 'Item No.', type: 'number', required: true },
                        { name: 'Product Code', type: 'text', required: true },
                        { name: 'Description', type: 'textarea', required: true },
                        { name: 'Quantity Ordered', type: 'number', required: true },
                        { name: 'Unit Price', type: 'currency', required: true, currency: 'TND' },
                        {
                            name: 'Stock Availability', type: 'select', required: true,
                            options: ['In Stock', 'To Order', 'Partial']
                        },
                        { name: 'Line Total', type: 'currency', calculated: true, readOnly: true }
                    ]
                },
                {
                    title: 'Order Summary',
                    fields: [
                        { name: 'Total Amount', type: 'currency', calculated: true, readOnly: true, currency: 'TND' },
                        { name: 'Deposit Required (if any)', type: 'currency', currency: 'TND' },
                        { name: 'Deposit Received', type: 'checkbox' },
                        { name: 'Receipt Number', type: 'text' }
                    ]
                },
                {
                    title: 'Processing',
                    fields: [
                        { name: 'Order Entered By', type: 'text', required: true },
                        { name: 'Credit Check Completed', type: 'checkbox', required: true },
                        { name: 'Stock Reserved', type: 'checkbox', required: true },
                        { name: 'Production/Purchase Initiated', type: 'checkbox' },
                        { name: 'Customer Notified', type: 'checkbox', required: true }
                    ]
                },
                {
                    title: 'Approvals',
                    fields: [
                        { name: 'Sales Rep Signature', type: 'signature', required: true },
                        { name: 'Manager Approval', type: 'signature', required: true },
                        { name: 'Finance Clearance (for credit orders)', type: 'signature', required: 'conditional' }
                    ]
                }
            ]
        },

        instructions: [
            'Verify quotation details match order',
            'Check customer credit status for credit orders',
            'Confirm stock availability or lead time',
            'Reserve stock immediately upon order confirmation',
            'Deposit required for new customers (50%) or large orders',
            'Notify customer of order confirmation and expected delivery',
            'Coordinate with operations for delivery scheduling'
        ],

        relatedDocuments: [
            'Sales & Customer Playbook',
            'Credit Policy',
            'Inventory Management Playbook'
        ]
    },

    {
        id: 'SALES-003',
        title: 'Customer Registration Form',
        department: 'Sales',
        category: 'Customer Management',
        version: '1.9',
        effectiveDate: '2024-01-15',
        description: 'Form for registering new customers in the system and establishing credit terms',

        formStructure: {
            sections: [
                {
                    title: 'Company Information',
                    fields: [
                        { name: 'Company Name', type: 'text', required: true },
                        { name: 'Legal Name (if different)', type: 'text' },
                        { name: 'Tax ID Number', type: 'text', required: true },
                        { name: 'Registration Number', type: 'text', required: true },
                        {
                            name: 'Business Type', type: 'select', required: true,
                            options: ['Industry', 'Commercial', 'Government', 'NGO', 'Individual']
                        },
                        { name: 'Industry Sector', type: 'text' }
                    ]
                },
                {
                    title: 'Contact Information',
                    fields: [
                        { name: 'Primary Address', type: 'textarea', required: true },
                        { name: 'City', type: 'text', required: true },
                        { name: 'Postal Code', type: 'text' },
                        { name: 'Phone', type: 'tel', required: true },
                        { name: 'Email', type: 'email', required: true },
                        { name: 'Website', type: 'text' }
                    ]
                },
                {
                    title: 'Primary Contact Person',
                    fields: [
                        { name: 'Full Name', type: 'text', required: true },
                        { name: 'Position', type: 'text', required: true },
                        { name: 'Direct Phone', type: 'tel', required: true },
                        { name: 'Mobile', type: 'tel' },
                        { name: 'Email', type: 'email', required: true }
                    ]
                },
                {
                    title: 'Financial Information',
                    fields: [
                        { name: 'Bank Name', type: 'text', required: true },
                        { name: 'Bank Account Number', type: 'text', required: true },
                        { name: 'Requested Credit Limit', type: 'currency', currency: 'TND' },
                        {
                            name: 'Requested Payment Terms', type: 'select',
                            options: ['Cash', 'Net 30', 'Net 60', 'Net 90']
                        },
                        { name: 'Trade References (3 required)', type: 'textarea' }
                    ]
                },
                {
                    title: 'How Did You Hear About Us?',
                    fields: [
                        {
                            name: 'Source', type: 'select', required: true,
                            options: ['Website', 'Referral', 'Social Media', 'Advertisement', 'Direct Visit', 'Other']
                        },
                        { name: 'Specific Referral (if applicable)', type: 'text' }
                    ]
                },
                {
                    title: 'Approval',
                    fields: [
                        { name: 'Customer Code (assigned)', type: 'text', autoGenerated: true },
                        { name: 'Registered By', type: 'text', required: true },
                        { name: 'Registration Date', type: 'date', defaultValue: 'today' },
                        { name: 'Sales Manager Approval', type: 'signature', required: true },
                        { name: 'Credit Limit Approved', type: 'currency', currency: 'TND' },
                        {
                            name: 'Payment Terms Approved', type: 'select',
                            options: ['Cash Only', 'Net 30', 'Net 60', 'Net 90']
                        },
                        { name: 'Finance Manager Approval', type: 'signature', required: 'conditional' }
                    ]
                }
            ]
        },

        instructions: [
            'Complete all required fields accurately',
            'Verify company registration documents',
            'Contact trade references for credit requests',
            'Sales manager approves customer registration',
            'Finance manager approves credit limits over 5,000 TND',
            'Assign customer code and file documentation',
            'Enter customer into system with approved terms'
        ],

        relatedDocuments: [
            'Sales & Customer Playbook',
            'Credit Policy',
            'Company Manual'
        ]
    },

    {
        id: 'SALES-004',
        title: 'Customer Complaint Form',
        department: 'Sales',
        category: 'Customer Service',
        version: '2.0',
        effectiveDate: '2024-01-15',
        description: 'Form for documenting and tracking customer complaints to resolution',

        formStructure: {
            sections: [
                {
                    title: 'Customer Information',
                    fields: [
                        { name: 'Customer Name', type: 'text', required: true },
                        { name: 'Customer Code', type: 'text' },
                        { name: 'Contact Person', type: 'text', required: true },
                        { name: 'Phone', type: 'tel', required: true },
                        { name: 'Email', type: 'email' }
                    ]
                },
                {
                    title: 'Complaint Details',
                    fields: [
                        { name: 'Complaint Number', type: 'text', autoGenerated: true },
                        { name: 'Date Received', type: 'date', required: true, defaultValue: 'today' },
                        {
                            name: 'Received Via', type: 'select', required: true,
                            options: ['Phone', 'Email', 'In Person', 'Social Media', 'Letter']
                        },
                        { name: 'Related Order/Service', type: 'text' },
                        {
                            name: 'Complaint Category', type: 'select', required: true,
                            options: ['Product Quality', 'Service Quality', 'Delivery Delay', 'Pricing', 'Staff Behavior', 'Other']
                        },
                        { name: 'Complaint Description', type: 'textarea', required: true, maxLength: 1000 },
                        { name: 'Customer Expected Resolution', type: 'textarea' }
                    ]
                },
                {
                    title: 'Investigation',
                    fields: [
                        { name: 'Assigned To', type: 'text', required: true },
                        { name: 'Investigation Findings', type: 'textarea', maxLength: 1000 },
                        { name: 'Root Cause', type: 'textarea', required: true },
                        {
                            name: 'Fault Determination', type: 'select', required: true,
                            options: ['Company Error', 'Customer Misunderstanding', 'Third Party Issue', 'No Fault', 'Under Review']
                        }
                    ]
                },
                {
                    title: 'Resolution',
                    fields: [
                        { name: 'Proposed Solution', type: 'textarea', required: true },
                        { name: 'Resolution Actions Taken', type: 'textarea', required: true },
                        {
                            name: 'Compensation Offered', type: 'select',
                            options: ['None', 'Apology', 'Discount', 'Refund', 'Replacement', 'Free Service', 'Other']
                        },
                        { name: 'Financial Impact (if any)', type: 'currency', currency: 'TND' },
                        { name: 'Resolution Date', type: 'date' },
                        {
                            name: 'Customer Satisfaction', type: 'select',
                            options: ['Satisfied', 'Partially Satisfied', 'Not Satisfied', 'Pending Feedback']
                        }
                    ]
                },
                {
                    title: 'Preventive Actions',
                    fields: [
                        { name: 'Preventive Action Required', type: 'checkbox' },
                        { name: 'Preventive Actions', type: 'textarea' },
                        { name: 'Training Needed', type: 'checkbox' },
                        { name: 'Process Improvement Required', type: 'checkbox' }
                    ]
                },
                {
                    title: 'Sign-Off',
                    fields: [
                        { name: 'Handled By', type: 'text', required: true },
                        { name: 'Manager Review', type: 'signature', required: true },
                        { name: 'Closure Date', type: 'date', autoFill: true }
                    ]
                }
            ]
        },

        instructions: [
            'Acknowledge complaint immediately (same day)',
            'Assign to appropriate person for investigation',
            'Investigate within 24 hours',
            'Propose resolution within 48-72 hours',
            'Update customer on progress',
            'Follow up after resolution to ensure satisfaction',
            'Identify root cause and preventive actions',
            'File complaint for trend analysis'
        ],

        relatedDocuments: [
            'Sales & Customer Playbook',
            'Complaint Handling Procedure',
            'Company Manual'
        ]
    },

    {
        id: 'SALES-005',
        title: 'Service Agreement Form',
        department: 'Sales',
        category: 'Contracts',
        version: '1.6',
        effectiveDate: '2024-01-15',
        description: 'Form for establishing maintenance service agreements with customers for regular fire equipment inspection and maintenance',

        formStructure: {
            sections: [
                {
                    title: 'Customer Information',
                    fields: [
                        { name: 'Customer Name', type: 'text', required: true },
                        { name: 'Customer Code', type: 'text', required: true },
                        { name: 'Site Address', type: 'textarea', required: true },
                        { name: 'Contact Person', type: 'text', required: true },
                        { name: 'Phone', type: 'tel', required: true },
                        { name: 'Email', type: 'email', required: true }
                    ]
                },
                {
                    title: 'Agreement Details',
                    fields: [
                        { name: 'Agreement Number', type: 'text', autoGenerated: true },
                        {
                            name: 'Agreement Type', type: 'select', required: true,
                            options: ['Annual Maintenance', 'Semi-Annual Inspection', 'Quarterly Service', 'Custom']
                        },
                        { name: 'Start Date', type: 'date', required: true },
                        { name: 'End Date', type: 'date', required: true },
                        { name: 'Contract Duration', type: 'text', calculated: true },
                        { name: 'Auto-Renewal', type: 'checkbox' }
                    ]
                },
                {
                    title: 'Equipment Covered',
                    type: 'repeatable',
                    fields: [
                        {
                            name: 'Equipment Type', type: 'select', required: true,
                            options: ['Fire Extinguishers', 'Fire Hose Reels', 'Fire Alarm System', 'Emergency Lighting', 'Other']
                        },
                        { name: 'Quantity', type: 'number', required: true },
                        { name: 'Location/Details', type: 'text', required: true },
                        {
                            name: 'Service Frequency', type: 'select', required: true,
                            options: ['Monthly', 'Quarterly', 'Semi-Annual', 'Annual']
                        }
                    ]
                },
                {
                    title: 'Service Scope',
                    fields: [
                        { name: 'Inspection Included', type: 'checkbox', required: true },
                        { name: 'Testing Included', type: 'checkbox', required: true },
                        { name: 'Refilling Included', type: 'checkbox' },
                        {
                            name: 'Repairs Included', type: 'select',
                            options: ['Not Included', 'Minor Repairs Only', 'All Repairs', 'Up to Limit']
                        },
                        {
                            name: 'Replacement Parts', type: 'select',
                            options: ['Cost Extra', 'Included in Fee', 'Up to Limit']
                        },
                        {
                            name: 'Emergency Response', type: 'select',
                            options: ['Not Included', '24h Response', '48h Response']
                        }
                    ]
                },
                {
                    title: 'Pricing',
                    fields: [
                        { name: 'Annual Service Fee', type: 'currency', required: true, currency: 'TND' },
                        {
                            name: 'Payment Terms', type: 'select', required: true,
                            options: ['Annual in Advance', 'Semi-Annual', 'Quarterly', 'Monthly']
                        },
                        {
                            name: 'Billing Method', type: 'select', required: true,
                            options: ['Invoice', 'Direct Debit', 'Bank Transfer']
                        },
                        { name: 'Special Discount Applied', type: 'number', min: 0, max: 20 }
                    ]
                },
                {
                    title: 'Terms & Conditions',
                    fields: [
                        {
                            name: 'Notice Period for Cancellation', type: 'select', required: true,
                            options: ['30 days', '60 days', '90 days']
                        },
                        { name: 'Late Payment Fee', type: 'text' },
                        { name: 'Liability Limitation', type: 'textarea' },
                        { name: 'Special Terms', type: 'textarea' }
                    ]
                },
                {
                    title: 'Signatures',
                    fields: [
                        { name: 'SS+ Representative', type: 'text', required: true },
                        { name: 'SS+ Signature', type: 'signature', required: true },
                        { name: 'Customer Representative', type: 'text', required: true },
                        { name: 'Customer Signature', type: 'signature', required: true },
                        { name: 'Agreement Date', type: 'date', required: true },
                        { name: 'Manager Approval', type: 'signature', required: true }
                    ]
                }
            ]
        },

        instructions: [
            'Conduct site survey before preparing agreement',
            'Clearly specify what is included and excluded',
            'Obtain customer signature on all terms',
            'Manager must approve pricing and terms',
            'Schedule service visits in advance',
            'Maintain equipment log for each customer',
            'Review and renew agreements 60 days before expiry'
        ],

        relatedDocuments: [
            'Sales & Customer Playbook',
            'Service Delivery Playbook',
            'Pricing Guidelines'
        ]
    },

    {
        id: 'SALES-006',
        title: 'Customer Credit Application',
        department: 'Sales',
        category: 'Credit',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Application for customer credit approval',
        formStructure: {
            sections: [
                { title: 'Customer', fields: [
                    { name: 'Company Name', type: 'text', required: true },
                    { name: 'Tax ID', type: 'text', required: true },
                    { name: 'Address', type: 'textarea', required: true },
                    { name: 'Phone', type: 'tel', required: true },
                    { name: 'Email', type: 'email', required: true }
                ]},
                { title: 'Credit Request', fields: [
                    { name: 'Requested Credit Limit (TND)', type: 'currency', required: true, currency: 'TND' },
                    { name: 'Requested Payment Terms', type: 'select', required: true, options: ['Net 15', 'Net 30', 'Net 60', 'Net 90'] },
                    { name: 'Primary Contact', type: 'text', required: true },
                    { name: 'Bank Reference', type: 'text' },
                    { name: 'Trade References', type: 'textarea', required: true }
                ]},
                { title: 'Approval', fields: [
                    { name: 'Sales Rep', type: 'text', required: true },
                    { name: 'Admin & Finance Verification', type: 'signature', required: true },
                    { name: 'Sales Responsible Approval', type: 'signature', required: true },
                    { name: 'Manager Approval', type: 'signature', required: 'conditional' }
                ]}
            ]
        },
        instructions: ['Collect company registration and tax certificate', 'Verify trade references', 'Approval per credit policy'],
        relatedDocuments: ['Sales & Customer Playbook', 'Payment Terms & Credit Policy']
    },
    {
        id: 'SALES-007',
        title: 'Sales Visit Report',
        department: 'Sales',
        category: 'Customer Relations',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Report of sales visit and customer contact',
        formStructure: {
            sections: [
                { title: 'Visit Details', fields: [
                    { name: 'Date', type: 'date', required: true },
                    { name: 'Sales Rep', type: 'text', required: true },
                    { name: 'Customer Name', type: 'text', required: true },
                    { name: 'Contact Person', type: 'text', required: true },
                    { name: 'Location', type: 'text', required: true },
                    { name: 'Visit Type', type: 'select', required: true, options: ['Cold Call', 'Follow-up', 'Quotation', 'Contract Review', 'Other'] }
                ]},
                { title: 'Outcome', fields: [
                    { name: 'Summary', type: 'textarea', required: true, maxLength: 1000 },
                    { name: 'Opportunities / Next Steps', type: 'textarea' },
                    { name: 'Quotation Issued', type: 'checkbox' },
                    { name: 'Quotation Number', type: 'text' }
                ]},
                { title: 'Sign-off', fields: [
                    { name: 'Sales Rep Signature', type: 'signature', required: true }
                ]}
            ]
        },
        instructions: ['Complete within 24 hours of visit', 'Share with manager if significant opportunity', 'Link to CRM if applicable'],
        relatedDocuments: ['Sales & Customer Playbook', 'Lead Management']
    },
    {
        id: 'SALES-008',
        title: 'Product Return Authorization',
        department: 'Sales',
        category: 'Returns',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Authorization for product returns',
        formStructure: {
            sections: [
                { title: 'Return Request', fields: [
                    { name: 'RMA Number', type: 'text', autoGenerated: true },
                    { name: 'Date', type: 'date', required: true, defaultValue: 'today' },
                    { name: 'Customer Name', type: 'text', required: true },
                    { name: 'Original Invoice Number', type: 'text', required: true },
                    { name: 'Reason', type: 'select', required: true, options: ['Defective', 'Wrong Item', 'Excess', 'Customer Change', 'Other'] },
                    { name: 'Description', type: 'textarea', required: true }
                ]},
                { title: 'Items', type: 'repeatable', fields: [
                    { name: 'Product Code', type: 'text', required: true },
                    { name: 'Description', type: 'text', required: true },
                    { name: 'Quantity', type: 'number', required: true },
                    { name: 'Condition', type: 'select', required: true, options: ['Unopened', 'Opened', 'Used', 'Damaged'] }
                ]},
                { title: 'Approval', fields: [
                    { name: 'Sales Rep', type: 'text', required: true },
                    { name: 'Sales Responsible Approval', type: 'signature', required: true }
                ]}
            ]
        },
        instructions: ['Issue RMA before return', 'Customer returns to Sfax or Tunis', 'Inspect upon receipt and process credit per policy'],
        relatedDocuments: ['Sales & Customer Playbook', 'Warranty & Returns Policy']
    },
    {
        id: 'SALES-009',
        title: 'Sales Target Setting Form',
        department: 'Sales',
        category: 'Performance',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Form to set and agree sales targets',
        formStructure: {
            sections: [
                { title: 'Period & Person', fields: [
                    { name: 'Period', type: 'select', required: true, options: ['Monthly', 'Quarterly', 'Annual'] },
                    { name: 'Period Start', type: 'date', required: true },
                    { name: 'Period End', type: 'date', required: true },
                    { name: 'Employee Name', type: 'text', required: true },
                    { name: 'Role', type: 'text', required: true }
                ]},
                { title: 'Targets', fields: [
                    { name: 'Revenue Target (TND)', type: 'currency', required: true, currency: 'TND' },
                    { name: 'New Customers Target', type: 'number', required: true },
                    { name: 'Service Contracts Target', type: 'number' },
                    { name: 'Other KPIs', type: 'textarea' }
                ]},
                { title: 'Agreement', fields: [
                    { name: 'Sales Responsible Signature', type: 'signature', required: true },
                    { name: 'Employee Signature', type: 'signature', required: true },
                    { name: 'Date', type: 'date', required: true }
                ]}
            ]
        },
        instructions: ['Set targets in line with company plan', 'Review quarterly', 'Used for performance appraisal'],
        relatedDocuments: ['Sales & Customer Playbook', 'People & Admin Playbook']
    },
    {
        id: 'SALES-010',
        title: 'Customer Feedback Survey',
        department: 'Sales',
        category: 'Customer Relations',
        version: '1.0',
        effectiveDate: '2024-01-15',
        description: 'Survey to collect customer feedback',
        formStructure: {
            sections: [
                { title: 'Customer', fields: [
                    { name: 'Customer Name', type: 'text', required: true },
                    { name: 'Contact Person', type: 'text', required: true },
                    { name: 'Date of Service / Interaction', type: 'date', required: true },
                    { name: 'Service Type', type: 'select', required: true, options: ['Inspection', 'Maintenance', 'Installation', 'Sales', 'Other'] }
                ]},
                { title: 'Feedback', fields: [
                    { name: 'Overall Satisfaction', type: 'rating', scale: '1-5', required: true },
                    { name: 'Quality of Work', type: 'rating', scale: '1-5' },
                    { name: 'Timeliness', type: 'rating', scale: '1-5' },
                    { name: 'Communication', type: 'rating', scale: '1-5' },
                    { name: 'Would Recommend', type: 'rating', scale: '1-5' },
                    { name: 'Comments', type: 'textarea', maxLength: 500 }
                ]},
                { title: 'Optional', fields: [
                    { name: 'Collected By', type: 'text' },
                    { name: 'Date', type: 'date', defaultValue: 'today' }
                ]}
            ]
        },
        instructions: ['Send after service completion or periodically', 'Use for improvement and recognition', 'Store with customer record'],
        relatedDocuments: ['Sales & Customer Playbook', 'Complaint Handling Process']
    }
];
